[package]
name = "mcparse"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
thiserror = "2.0.3"
miette = { version = "7.4.0", features = ["fancy"] }
owo-colors = "4.1.0"
